GET http://localhost:3000/ads?category=autre

###

GET http://localhost:3000/categories?name=a

###

GET http://localhost:3000/categories?name=a

###

POST http://localhost:3000/ads
Content-type: application/json

  {
    "title": "Eventail category",
    "description": "De ma mamie 100",
    "owner": "eventailmamie@gmail.com",
    "price": 100,
    "picture":
      "https://eventail.jpg",
    "location": "Bordeaux",
    "categoryId": 1
  }

###
DELETE http://localhost:3000/ads/24

###
PUT http://localhost:3000/ads/1
Content-type: application/json

  {
    "category": 1
  }