GET http://localhost:3000/ads

###
GET http://localhost:3000/ads?category=autre

###
GET http://localhost:3000/categories?name=a

###
POST http://localhost:3000/ads
Content-type: application/json

  {
    "title": "Objet test tag 10",
    "description": "Nouvel objet mysterieux",
    "owner": "mysterio@gmail.com",
    "price": 999,
    "picture":
      "https://mystere.jpg",
    "location": "Mystere",
    "category": 1,
    "tags": [{"id":11}]
  }
  
###
PUT http://localhost:3000/ads/2
Content-type: application/json

  {
    "tag": [{"id":1},{"id":2},{"id":3}]
  }

###
DELETE http://localhost:3000/ads/24